apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: kube-state-metrics
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/scrape: 'true'
spec:
  ports:
    - port: {{ .Values.service.kubeStateMetrics.externalPort }}
      targetPort: {{ .Values.service.kubeStateMetrics.internalPort }}
      protocol: TCP
      name: kube-state-metrics
  selector:
{{ include "labels.kubeStateMetrics" . | indent 4 }}
