apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/scrape: 'true'
  name: {{ .Values.service.prometheusNodeExporter.name }}
  namespace: {{ .Values.namespace }}
  labels:
{{ include "labels.nodeExporter" . | indent 4 }}
spec:
  type: {{ .Values.service.prometheusNodeExporter.type }}
  clusterIP: {{ .Values.service.prometheusNodeExporter.clusterIP }}
  ports:
    - port: {{ .Values.service.prometheusNodeExporter.externalPort }}
      targetPort: {{ .Values.service.prometheusNodeExporter.internalPort }}
      protocol: TCP
      name: node-exporter
  selector:
{{ include "labels.nodeExporter" . | indent 4 }}
