apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: prometheus
  labels:
{{ include "labels" . | indent 4 }}
  annotations:
    prometheus.io/probe: "true"
    prometheus.io/scrape: 'true'
spec:
  type: {{ .Values.service.prometheus.type }}
  ports:
    - port: {{ .Values.service.prometheus.externalPort }}
      targetPort: {{ .Values.service.prometheus.internalPort }}
{{- if .Values.selectPort }}
      nodePort: {{ .Values.service.prometheus.nodePort }}
{{- end }}
      protocol: TCP
      name: core
  selector:
{{ include "labels.prometheus" . | indent 4 }}
